export const GET_ALL_BEERS = "GET_ALL_BEERS";
export const SEARCH_FOR_BEERS = "SEARCH_FOR_BEERS";
export const ADD_TO_FAVORITES = "ADD_TO_FAVORITES";
export const REMOVE_FROM_FAVORITES = "REMOVE_FROM_FAVORITES";
export const GET_RECOMMENDATIONS = "GET_RECOMMENDATIONS";
export const CLEAR_RECOMMENDATIONS = "CLEAR_RECOMMENDATIONS";